# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Brunton Diff Eqs
author: Udesh Habaraduwa
logo: ddse.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# LaTeX settings for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# HTML settings
html:
  mathjax: true
  use_issues_button: true
  use_repository_button: true
  extra_css:
    - custom.css

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/onedeeper/ddse-in-julia  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Enable MyST extensions for advanced Markdown features like tooltips
parse:
  myst_enable_extensions:
    # - deflist
    # - colon_fence
    # - html_admonition
    # - html_image
    # - linkify
    # - substitution
    # - tasklist
    # - tooltip
    - amsmath
    - dollarmath

sphinx:
  extra_css: ["custom.css"]